"""ozgarish

Revision ID: 94cd75d1f91b
Revises: 9e930759cedb
Create Date: 2024-10-28 20:29:42.271161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94cd75d1f91b'
down_revision: Union[str, None] = '9e930759cedb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'adress',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'jinsi',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'jinsi',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'adress',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
